[programs.localnet]
mysolanaapp = "4FKLNRC1Gm57NjPmbNg6afBwWJoiNzgHLBv26mw2sFN8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jeffdimarco/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
